### ISSUE TITLE
Synchronize scrolling of Markdown editing view and slide preview view

### ISSUE THREAD

**Issue by calmwaves111** [samuele-cozzi/obsidian-marp-slides#124]
I hope this message finds you well. I wanted to reach out and kindly request a new feature for the project. Specifically, I would like to propose the addition of synchronized scrolling functionality between the Markdown editing view and the slide preview view，Similar to vscode's marp plugin

I believe this feature would not only save time but also improve the overall usability of the project for many users, especially those who frequently work with Markdown-based presentations.

Thank you for considering my suggestion, and please let me know if there is any additional information or clarification needed. I'm looking forward to hearing your thoughts on this proposal.

**Comment by samuele-cozzi** [comment]
Thank you for your interest and engagement with the project; your support is greatly appreciated!
It's one of the features I had envisioned for the initial version of the plugin, but unfortunately, it turned out to be more challenging than anticipated. If interest in this plugin continues to grow, I will strive to develop this feature.

**Comment by PKDmeDEV** [comment]
Hi.
Thanks for this plugin. I also wanted to have this feature.
For the implementation part, I assume you might have already looked into Advanced Slides plugin, it has that feature. 

Thanks

**Comment by PKDmeDEV** [comment]
Hi,
I updated the plugin, but it breaks the theme. I am no longer able to use `beamer` theme. 

Kindly check
